spring:
  datasource:
    url: jdbc:mysql://192.168.11.11:3306/batch
    username: homestead
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver


  sql:
    init:
      schema-locations: classpath:/org/springframework/batch/core/schema-mysql.sql

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false